rolebindings:

- groups: 
  - group-1
  - group-2
  namespaces:
  - fooproject
  - barproject
  clusterroles:
  - system:aggregate-to-edit
  - system:openshift:aggregate-to-edit
  - project-helm-chartrepository-editor
  roles:
  - myrole
  - myotherroles

- groups:
  - group-3
  users:
  - user-1
  - user-2
  serviceAccounts:
  - namespace: default
    name: test
  - namespace: myproject
    name: mysa
  namespaces:
  - default
  roles:
  - myrole
  