{{- /* Find subdirectories "/files/secrets/*" */ -}}
{{- $dirs := list }}
{{- range $path, $_ :=  .Files.Glob  "files/secrets/*/*" }}
  {{- $dirs = append $dirs (dir $path)}}
{{- end }}
{{- $dirs =  ($dirs | uniq) }}

{{- range $dirs }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ base . }}
type: Opaque
data:
{{- range $path, $_ :=  $.Files.Glob (print . "/*") }}
{{- if eq (ext $path) ".aes" }}
  {{ base $path | trimSuffix ".aes" }}: |-
    {{- $.Files.Get $path | decryptAES $.Values.aeskey | b64enc | nindent 4 }}
{{- else }}
  {{ base $path }}: |-
    {{- $.Files.Get $path | b64enc | nindent 4 }}
{{- end }}
{{- end }}
---
{{- end }}